# Generated by Django 5.0.7 on 2024-10-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStudent',
            fields=[
                ('reg_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
            ],
            options={
                'db_table': 'application_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='defalut_email_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'application_defalut_email_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_role', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('company_skill', models.CharField(max_length=255)),
                ('company_eligibility', models.FloatField()),
                ('company_eligibility_dept', models.CharField(max_length=255)),
                ('company_academic_year', models.CharField(max_length=255)),
                ('company_opening_date', models.DateField(blank=True, null=True)),
                ('company_last_date', models.DateField(blank=True, null=True)),
                ('company_ctc', models.CharField(blank=True, max_length=255, null=True)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('company_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement_User',
            fields=[
                ('faculty_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_dept', models.CharField(max_length=100)),
                ('faculty_email', models.CharField(max_length=100)),
                ('faculty_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_regno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_dob', models.DateField(blank=True, null=True)),
                ('student_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(blank=True, max_length=3, null=True)),
                ('round1', models.CharField(blank=True, max_length=5, null=True)),
                ('round2', models.CharField(blank=True, max_length=5, null=True)),
                ('round3', models.CharField(blank=True, max_length=5, null=True)),
                ('round4', models.CharField(blank=True, max_length=5, null=True)),
                ('placement_offer', models.CharField(blank=True, max_length=3, null=True)),
                ('ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('student_reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Willingness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willingness', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
