# Generated by Django 5.0.7 on 2024-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement_user',
            name='faculty_role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
