# Generated by Django 5.0.7 on 2024-10-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_placement_user_faculty_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_user',
            name='faculty_role',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
