# Generated by Django 5.0.7 on 2024-10-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_placement_user_faculty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_offer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
