# Generated by Django 5.0.7 on 2024-10-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_placement_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_eligibility_dept',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_academic_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_eligibility',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DepartmentEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_departments', to='core.company')),
            ],
        ),
    ]
