# Generated by Django 5.0.7 on 2024-10-14 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_company_company_eligibility_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenteligibility',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_academic_year',
            field=models.CharField(max_length=150),
        ),
    ]
