# Generated by Django 5.0.7 on 2024-10-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_departmenteligibility_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_eligibility',
            field=models.FloatField(),
        ),
    ]
