# Generated by Django 5.0.7 on 2024-10-16 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_company_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCompanyDetails',
            fields=[
                ('training_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_place', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_academic_year', models.CharField(max_length=150)),
                ('company_opening_date', models.DateField(blank=True, null=True)),
                ('company_last_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCompanyDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_departments', to='core.trainingcompanydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_gender', models.CharField(max_length=10)),
                ('topics', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='core.trainingcompanydetails')),
            ],
        ),
    ]
