# Generated by Django 5.0.7 on 2024-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_placement_company_type_placement_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='job_domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
