# Generated by Django 5.0.7 on 2024-10-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_placement_job_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_content', models.IntegerField()),
                ('lecture_sessions', models.IntegerField()),
                ('practical_sessions', models.IntegerField()),
                ('interactive_sessions', models.IntegerField()),
                ('course_material', models.IntegerField()),
                ('usefulness', models.IntegerField()),
                ('knowledge_improvement', models.CharField(max_length=10)),
                ('timely_communication', models.IntegerField()),
                ('overall_arrangement', models.IntegerField()),
                ('content_relevance', models.CharField(max_length=3)),
                ('resource_person', models.CharField(max_length=3)),
                ('liked_topic', models.TextField()),
                ('specific_feedback', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainer')),
            ],
        ),
    ]
