# Generated by Django 5.0.7 on 2024-10-17 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
