# Generated by Django 5.0.7 on 2024-10-17 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_experience_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
