# Generated by Django 4.2.5 on 2024-10-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('post_date', models.CharField(max_length=100)),
                ('image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_post', models.DateField()),
            ],
        ),
    ]
