# Generated by Django 4.2.5 on 2024-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_studentresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresume',
            name='resume_file',
            field=models.FileField(upload_to=''),
        ),
    ]
