# Generated by Django 4.2.5 on 2024-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_studentresume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_eligibility_diploma',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_eligibility_hsc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_eligibility_sslc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='history_of_arrear',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='no_standing_arrear',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
