# Generated by Django 4.2.5 on 2024-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_company_company_eligibility_diploma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_eligibility_diploma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_eligibility_hsc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_eligibility_sslc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
