# Generated by Django 4.2.5 on 2024-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_company_company_eligibility_diploma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='history_of_arrear',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
