# Generated by Django 5.0.6 on 2024-11-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_company_history_of_arrear'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationstudent',
            table='application_student_cgpa',
        ),
    ]
