# Generated by Django 5.0.6 on 2024-12-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_applicationstudent_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationstudent',
            table='application_student',
        ),
    ]
